### ISSUE TITLE
Binder fails to build (UnsatisfiableError)

### ISSUE THREAD

**Issue by liamtoney** [GenericMappingTools/gmt-python#258] opened 2018-12-24 08:40 UTC
**Description of the problem**

The [online Binder demo](http://try.gmtpython.xyz/) fails to build. Specifically, when trying to solve the environment, it fails with the error:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - gmt=6.0.0a16
Use "conda info <package>" to see the dependencies for each package.
```
From past experience with Binder, I'm guessing this is just a temporary thing to do with specifications given in [`environment.yml`](https://github.com/GenericMappingTools/gmt-python/blob/master/environment.yml). Maybe changing [this line](https://github.com/GenericMappingTools/gmt-python/blob/61a6e14fbb7b61f4c381b591dffad532812dd6b0/environment.yml#L8) in that file to pin something more specific than `6.0.0*` would help?

**Full error message**

<details>
<summary>Click to show build logs...</summary>

```
Waiting for build to start...

 ---> Using cache
 ---> 2e95b130e1bd
Step 7/35 : ENV LANGUAGE en_US.UTF-8
 ---> Using cache
 ---> 7f9496f55171
Step 8/35 : ENV SHELL /bin/bash
 ---> Using cache
 ---> 77ed5dc8a561
Step 9/35 : ARG NB_USER
 ---> Using cache
 ---> a7f9afcd32d4
Step 10/35 : ARG NB_UID
 ---> Using cache
 ---> 8a12d91d1b09
Step 11/35 : ENV USER ${NB_USER}
 ---> Using cache
 ---> a80555c3d052
Step 12/35 : ENV HOME /home/${NB_USER}
 ---> Using cache
 ---> 67e51708ea4f
Step 13/35 : RUN adduser --disabled-password     --gecos "Default user"     --uid ${NB_UID}     ${NB_USER}
 ---> Using cache
 ---> 23d6c95651f8
Step 14/35 : WORKDIR ${HOME}
 ---> Using cache
 ---> e5fb9b79e71d
Step 15/35 : RUN wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key |  apt-key add - &&     DISTRO="bionic" &&    echo "deb https://deb.nodesource.com/node_10.x $DISTRO main" >> /etc/apt/sources.list.d/nodesource.list &&     echo "deb-src https://deb.nodesource.com/node_10.x $DISTRO main" >> /etc/apt/sources.list.d/nodesource.list
 ---> Using cache
 ---> 501962e52ffe
Step 16/35 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends        less        nodejs        unzip        > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> a5dc74b82cf6
Step 17/35 : EXPOSE 8888
 ---> Using cache
 ---> 7a7c76ee6fca
Step 18/35 : ENV APP_BASE /srv
 ---> Using cache
 ---> d9dcad610e1e
Step 19/35 : ENV CONDA_DIR ${APP_BASE}/conda
 ---> Using cache
 ---> 2ca509a49205
Step 20/35 : ENV NB_PYTHON_PREFIX ${CONDA_DIR}
 ---> Using cache
 ---> 88d419f5af05
Step 21/35 : ENV KERNEL_PYTHON_PREFIX ${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> a01957c0d475
Step 22/35 : ENV PATH ${CONDA_DIR}/bin:$HOME/.local/bin:${PATH}
 ---> Using cache
 ---> 55cc4f0e8438
Step 23/35 : COPY conda/install-miniconda.bash /tmp/install-miniconda.bash
 ---> Using cache
 ---> 4712b15850d8
Step 24/35 : COPY conda/environment.py-3.6.frozen.yml /tmp/environment.yml
 ---> Using cache
 ---> 712445c96140
Step 25/35 : RUN bash /tmp/install-miniconda.bash && rm /tmp/install-miniconda.bash /tmp/environment.yml
 ---> Using cache
 ---> 5aa583bad4ed
Step 26/35 : USER root
 ---> Using cache
 ---> d4d5afa601c9
Step 27/35 : COPY src/ ${HOME}
 ---> 3dda7aa29056
Step 28/35 : RUN chown -R ${NB_USER}:${NB_USER} ${HOME}
 ---> Running in a872b14851bf
Removing intermediate container a872b14851bf
 ---> b0bf64f678b5
Step 29/35 : USER ${NB_USER}
 ---> Running in b4bc1de4e871
Removing intermediate container b4bc1de4e871
 ---> 71df06f402cd
Step 30/35 : RUN conda env update -n root -f "environment.yml" && conda clean -tipsy && conda list -n root
 ---> Running in 153f560812bb
Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gmt=6.0.0a16
Use "conda info <package>" to see the dependencies for each package.

Removing intermediate container 153f560812bb
The command '/bin/sh -c conda env update -n root -f "environment.yml" && conda clean -tipsy && conda list -n root' returned a non-zero code: 1Error during build: __init__() missing 1 required positional argument: 'build_log'
```
</details>
</br>

**System information**

* Operating system: macOS Mojave 10.14.1
* Browser: Google Chrome 72.0.3626.28

**Comment by seisman** [comment] 2018-12-24 15:58
Duplicate of #234.

**Closed by seisman** 2018-12-24 15:58 UTC
Labels: duplicate
