### ISSUE TITLE
gmt.exceptions.GMTCLibNotFoundError

### ISSUE THREAD

**Issue by shaunwbell** [GenericMappingTools/gmt-python#202] opened 2018-06-28 18:18 UTC
## Full code/command that generated the error
After a fresh install based upon the installation docs...
Just running through the basic Jupyter First Steps Notebook the code fails in the fig.show() command.

My notebook where you can see the error message is at https://github.com/NOAA-PMEL/EcoFOCI_Jupyter_Notebooks/blob/master/2018/Mapping%20Examples/Python-GMT%20Failed.ipynb

## Full error message
`psconvert [ERROR]: System call [gs -q -dSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -dMaxBitmap=2147483647 -dUseFastColor=true '/Volumes/WDC_internal/Users/bell/.gmt/sessions/gmt6.32329/gmt_1.ps-' 2> './psconvert_32329c.bb'] returned error 256.
`

in ipython after running the gmt.test() package gives the following failure:   

```
==================================================================================== FAILURES =====================================================================================
______________________________________________________________________________ test_load_libgmt_fail ______________________________________________________________________________

    def test_load_libgmt_fail():
        "Test that loading fails when given a bad library path."
        env = {"GMT_LIBRARY_PATH": "not/a/real/path"}
        with pytest.raises(GMTCLibNotFoundError):
>           load_libgmt(env=env)
E           Failed: DID NOT RAISE <class 'gmt.exceptions.GMTCLibNotFoundError'>

anaconda2/envs/gmt-python/lib/python3.6/site-packages/gmt/tests/test_clib.py:84: Failed
====================================================================== 1 failed, 138 passed in 56.73 seconds ======================================================================
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-84e7c468e870> in <module>()
----> 1 gmt.test()

~/anaconda2/envs/gmt-python/lib/python3.6/site-packages/gmt/__init__.py in test(doctest, verbose, coverage, figures)
    103     args.append("gmt")
    104     status = pytest.main(args)
--> 105     assert status == 0, "Some tests have failed."
```

## System information

* Operating system: OSX 10.13.15
* Python installation (Anaconda, system, ETS): Anaconda
* Version of GMT/Python: GMT=6.0.0a16 / python=3.6.5
* How you installed GMT/Python: conda and pip for gmt-python

**Comment by leouieda** [comment] 2018-06-29 21:49
Hi @shaunwbell, thanks for reporting the error. I think these are actually two different failures. I'll need some more information to try to reproduce this. Could you please post the output of:

1. In Python: `gmt.print_libgmt_info()`
2. On the terminal: `conda list`

**Comment by shaunwbell** [comment] 2018-07-02 13:39
1.  from within jupyter notebook
```
==================================================== Currently loaded libgmt =====================================================
binary dir: /Volumes/WDC_internal/Users/bell/anaconda2/envs/gmt-python/bin
cores: 8
grid layout: rows
image layout: 
library path: /Volumes/WDC_internal/Users/bell/anaconda2/envs/gmt-python/lib/libgmt.dylib
padding: 2
plugin dir: /Volumes/WDC_internal/Users/bell/anaconda2/envs/gmt-python/lib/gmt/plugins
share dir: /Volumes/WDC_internal/Users/bell/anaconda2/envs/gmt-python/share/gmt
version: 6.0.0
```

2. from `conda list`

```
# Name                    Version                   Build  Channel
alabaster                 0.7.11                   py36_2    conda-forge
appnope                   0.1.0                    py36_0    conda-forge
asn1crypto                0.24.0                   py36_0    conda-forge
astroid                   1.6.5                    py36_0    conda-forge
atomicwrites              1.1.5                    py36_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
babel                     2.6.0                    py36_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.1.3                      py_0    conda-forge
bokeh                     0.12.16                  py36_0    conda-forge
boost                     1.66.0                   py36_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
bottleneck                1.2.1            py36h7eb728f_1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
cftime                    1.0.0                    py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                        py_1    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
cmocean                   1.1                        py_0    conda-forge
cryptography              2.2.1                    py36_0    conda-forge
curl                      7.60.0               h93b3f91_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cytoolz                   0.9.0.1                  py36_0    conda-forge
dask                      0.18.1                     py_0    conda-forge
dask-core                 0.18.1                     py_0    conda-forge
dcw-gmt                   1.1.3                         0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
distributed               1.22.0                   py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
erddapy                   0.1.7                      py_0    conda-forge
expat                     2.2.5                         0    conda-forge
fftw                      3.3.7                         0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
freexl                    1.0.5                         0    conda-forge
gdal                      2.2.4                    py36_0    conda-forge
geos                      3.6.2                hfc679d8_2    conda-forge
geotiff                   1.4.2                hb54a4aa_1    conda-forge
gettext                   0.19.8.1                      0    conda-forge
ghostscript               9.22                          0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.55.0                        0    conda-forge
gmt                       6.0.0a16        blas_openblas_200  [blas_openblas]  conda-forge/label/dev
gmt-python                0+unknown                 <pip>
gshhg-gmt                 2.3.7                         0    conda-forge
h5netcdf                  0.6.1                      py_0    conda-forge
h5py                      2.8.0            py36h470a237_0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py36_0    conda-forge
imagesize                 1.0.0                    py36_0    conda-forge
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
isort                     4.3.4                    py36_0    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jpeg                      9b                            2    conda-forge
json-c                    0.12.1                        0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_client            5.2.3                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.9                hfc679d8_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
krb5                      1.14.6                        0    conda-forge
lazy-object-proxy         1.3.1                    py36_0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.2.4                         4    conda-forge
libgfortran               3.0.0                         0    conda-forge
libgfortran-ng            3.0.1                h93005f0_2  
libiconv                  1.15                 h470a237_1    conda-forge
libkml                    1.3.0                         6    conda-forge
libnetcdf                 4.6.1                         2    conda-forge
libpng                    1.6.34                        0    conda-forge
libpq                     9.6.3                         0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libspatialite             4.3.0a                       19    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libtiff                   4.0.9                he6b73bb_0    conda-forge
libxml2                   2.9.8                         0    conda-forge
locket                    0.2.0                    py36_1    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
mistune                   0.8.3                    py36_1    conda-forge
more-itertools            4.2.0                      py_0    conda-forge
msgpack-python            0.5.6            py36h2d50403_2    conda-forge
nb_conda_kernels          2.1.0                    py36_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
netcdf4                   1.4.0                    py36_0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.5.0                    py36_0    conda-forge
numpy                     1.14.5          py36_blas_openblashd3ea46f_200  [blas_openblas]  conda-forge
numpydoc                  0.8.0                    py36_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.3.0                         2    conda-forge
openssl                   1.0.2o                        0    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.1                   py36_0    conda-forge
pandoc                    2.2.1                hde52d81_0    conda-forge
pandocfilters             1.4.2                    py36_0    conda-forge
parso                     0.2.1                      py_0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
pcre                      8.41                          1    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
pluggy                    0.6.0                      py_0    conda-forge
poppler                   0.61.1                        3    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.6                    py36_0    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
py                        1.5.3                      py_0    conda-forge
pycodestyle               2.4.0                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pylint                    1.9.2                    py36_0    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_5    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
pytest                    3.6.2                    py36_0    conda-forge
pytest-mpl                0.9                        py_0    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
python.app                1.2                      py36_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     17.0.0                   py36_4    conda-forge
qt                        5.6.2                h9e3eb04_4    conda-forge
qtawesome                 0.4.4                    py36_0    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.4.2            py36h8a2030e_0    conda-forge
readline                  7.0                           0    conda-forge
requests                  2.19.1                   py36_0    conda-forge
rope                      0.10.7                   py36_0    conda-forge
scipy                     1.1.0           py36_blas_openblas_200  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                39.2.0                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
sortedcontainers          2.0.4                    py36_0    conda-forge
sphinx                    1.7.5                    py36_0    conda-forge
sphinxcontrib-websupport  1.1.0                    py36_0    conda-forge
spyder                    3.2.8                    py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.6.7                         0    conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.23                     py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5.1                    py36_0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xarray                    0.10.7                   py36_0    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
zeromq                    4.2.5                         1    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by leouieda** [comment] 2018-07-02 22:01
@shaunwbell thanks for the info. I'll try to reproduce it here. I can't see anything obviously wrong but I might be missing something.

**Comment by leouieda** [comment] 2018-07-14 20:15
OK, that narrows the problem down a bit, thanks! I wasn't able to reproduce the error on my machine or the CI systems. From the notebook traceback, it seems that the error is coming from ghostscript (which is what GMT uses to convert their postscript output to png).

Could you please try running:

```
conda update -c conda-forge ghostscript
```

This will try to update the ghostscript package.

**Comment by shaunwbell** [comment] 2018-07-16 15:00
`# All requested packages already installed.`

I removed by copy of ghostscript installed under homebrew as well to make sure there were no underlying conflicts... no change.

**Comment by leouieda** [comment] 2018-07-25 20:12
OK, this seems to be a problem with GMT messing up the postscript building. Could you try to remove all folders in the `~/.gmt/sessions` folder. This will clear away any junk that got left behind.

**Comment by shaunwbell** [comment] 2018-07-26 14:48
Removed that folder, went to reinstall from scratch and received the same error as #218 

```
GMTCLibNotFoundError: Error loading the GMT shared library '/Volumes/WDC_internal/Users/bell/anaconda2/envs/gmt-python_v2/lib/libgmt.dylib':
dlopen(/Volumes/WDC_internal/Users/bell/anaconda2/envs/gmt-python_v2/lib/libgmt.dylib, 6): Library not loaded: @rpath/libpoppler.71.dylib
  Referenced from: /Volumes/WDC_internal/Users/bell/anaconda2/envs/gmt-python_v2/lib/libgdal.20.dylib
  Reason: image not found
```

current libpoppler versions are .78 in my install

**Comment by leouieda** [comment] 2018-07-30 23:36
@shaunwbell don't worry about :) This has been a nightmare for the past week. Some of our dependencies broken on conda-forge because they are transitioning to a new compiler system. So the latest GMT6 build is incompatible with them but we need it to run GMT/Python. I'm trying to get this fixed as soon as possible.

**Comment by leouieda** [comment] 2018-07-30 23:45
@shaunwbell please see #221 for some updates on this. I'll close this for now and hope that #221 fixes the problems. If not, we can re-open this.

**Closed by leouieda** 2018-07-30 23:45 UTC
Labels: bug
